# Generated by Django 4.2.14 on 2025-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_scheduled',
            field=models.BooleanField(default=False, help_text='True if this is a scheduled ride, False for immediate'),
        ),
        migrations.AddField(
            model_name='ride',
            name='scheduled_pickup_time',
            field=models.DateTimeField(blank=True, help_text='When the rider wants to be picked up', null=True),
        ),
    ]
