# Generated by Django 4.2.14 on 2025-07-13 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideon', '0002_ride_is_scheduled_ride_scheduled_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='RideMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('driver_arrival', 'Driver Arrival Notification'), ('general', 'General Message'), ('pickup_delay', 'Pickup Delay'), ('route_change', 'Route Change')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rideon.ride')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
