# Generated by Django 4.2.14 on 2025-07-12 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_created_at_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
